import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(ROOT_DIR, 'nayra.config.json');
const COMPONENTS_DIR = path.join(ROOT_DIR, 'src', 'components');
const INDEX_FILE = path.join(ROOT_DIR, 'src', 'index.ts');

function generateExports() {
  // Leer configuración
  let prefix = 'Na';
  if (fs.existsSync(CONFIG_PATH)) {
    try {
      const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
      if (config.componentPrefix) {
        prefix = config.componentPrefix;
      }
    } catch (e) {
      console.warn('⚠️ No se pudo leer nayra.config.json, usando prefijo por defecto: "Na"');
    }
  }

  const rootExportsLines = [
    `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.`,
    `// This file is generated by scripts/generate-exports.ts before build.`,
    `import './assets/css/main.css';`,
    ``,
    `export * from './config';`,
  ];

  const componentsIndexLines = [
    `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.`,
    `// This file is generated by scripts/generate-exports.ts before build.`,
  ];

  const atomicDirs = ['atoms', 'molecules', 'organisms', 'templates'];
  let componentsFound = false;

  for (const atomicDir of atomicDirs) {
    const dirPath = path.join(COMPONENTS_DIR, atomicDir);
    if (!fs.existsSync(dirPath)) continue;

    const items = fs.readdirSync(dirPath);
    const atomicExportsLines = [
      `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.`,
      `// This file is generated by scripts/generate-exports.ts before build.`,
    ];
    let hasComponents = false;

    for (const item of items) {
      if (item === 'index.ts') continue;
      const itemPath = path.join(dirPath, item);
      if (fs.statSync(itemPath).isDirectory()) {
        const componentName = item;
        const prefixedName = `${prefix}${componentName}`;
        
        // Export interno (sin prefijo) para src/components/atoms/index.ts
        atomicExportsLines.push(`export * from './${componentName}';`);
        
        // Export externo (con prefijo) para src/index.ts
        rootExportsLines.push(
          `export { ${componentName} as ${prefixedName} } from './components/${atomicDir}/${componentName}';`
        );
        hasComponents = true;
        componentsFound = true;
      }
    }

    if (hasComponents) {
      fs.writeFileSync(path.join(dirPath, 'index.ts'), atomicExportsLines.join('\n') + '\n', 'utf-8');
      componentsIndexLines.push(`export * from './${atomicDir}';`);
    }
  }

  if (componentsFound) {
    fs.writeFileSync(path.join(COMPONENTS_DIR, 'index.ts'), componentsIndexLines.join('\n') + '\n', 'utf-8');
  }

  // Escribir src/index.ts
  fs.writeFileSync(INDEX_FILE, rootExportsLines.join('\n') + '\n', 'utf-8');
  console.log(`✅ Exports y Barrel Files generados correctamente con el prefijo "${prefix}".`);
}

generateExports();

